# Generated by Django 5.0.4 on 2024-04-22 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadesMedicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEspecialidade', models.CharField(max_length=98)),
                ('iconeEspecialidade', models.ImageField(blank=True, null=True, upload_to='icones')),
            ],
        ),
        migrations.CreateModel(
            name='DatasAbertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('agendado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DadosMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.IntegerField()),
                ('nomeMedico', models.CharField(max_length=98)),
                ('logradouro', models.CharField(max_length=44)),
                ('rua', models.CharField(max_length=62)),
                ('bairro', models.CharField(max_length=44)),
                ('numero', models.IntegerField()),
                ('cep', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=62)),
                ('estado', models.CharField(max_length=44)),
                ('rg', models.ImageField(upload_to='docs_pessoais')),
                ('crmID', models.ImageField(upload_to='crm')),
                ('foto', models.ImageField(upload_to='foto_perfil')),
                ('descricao', models.TextField()),
                ('valor_consulta', models.FloatField(default=530)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medicos.especialidadesmedicas')),
            ],
        ),
    ]
